### ISSUE TITLE
write it as a blog example

### ISSUE THREAD

**Issue by spyhole** [tjmonsi/small-site#1]

**Comment by tjmonsi** [comment]
Yep will do thanks :)

**Comment by spyhole** [comment]
yes! its its fate.i think.

google lack of blog example.  just vs rails, but nobody using polymer believe it.

and the promotion of polymer vs react, vue and its angular is very poor.

**Comment by ghost** [comment]
thx,tjmonsi

**Comment by tjmonsi** [comment]
@spyhole sorry if i am not responding, we are still working on making this a bit more robust (by deploying it on several projects and looking at problems we encounter while using it)

Hopefully I can have time to write a blog about it

**Comment by ghost** [comment]
i'm learning you web article step by step
