### ISSUE TITLE
in the small-site/README.md

### ISSUE THREAD

**Issue by singerswong** [tjmonsi/small-site#4]
in the package.json file
change the name of the project
change description of the project
change the version of the project
update the git url
in the src/manifest.json file  <-now, there is not this file, i cannot find it
change the name of the project
change the short name (max 20 characters) of the project
change start_url of the project
change display
change theme_color
change background_color
set the icons

**Comment by cerebrowang** [comment]
pls help me to close this.

**Comment by singerswang** [comment]
.
